name: Deploy to Vuepress
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1

    - name: build and Deploy
      run: bash deploy.sh
      shell: bash
      
