name: Deploy to Vuepress
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      env:
        ACCESS_TOKEN: ${{ secrets.access_token }}
      run: |
        npm install
        node -v
        npm -v
        ls
        bash ./deploy.sh
      
